spring:
  application:
    name: liquibase-demo
  datasource:
    hikari:
      connection-test-query: 'SELECT 1'
      maximum-pool-size: 5
      minimum-idle: 1
      validation-timeout: 3000
      max-lifetime: 250000
    username: 'demo'
    password: 'demo'
    url: 'jdbc:postgresql://localhost:5431/demo'
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc.lob.non_contextual_creation: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
